# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-05-29 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MojoMailManUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=256)),
                ('homedir', models.CharField(max_length=256)),
                ('email1', models.CharField(max_length=256)),
                ('email1_smpt_server', models.CharField(max_length=256)),
                ('email1_imap_server', models.CharField(max_length=256)),
                ('email1_pop3_server', models.CharField(max_length=256)),
                ('email1_password', models.CharField(max_length=256)),
                ('email2', models.CharField(max_length=256)),
                ('email2_smpt_server', models.CharField(max_length=256)),
                ('email2_imap_server', models.CharField(max_length=256)),
                ('email2_pop3_server', models.CharField(max_length=256)),
                ('email2_password', models.CharField(max_length=256)),
                ('email3', models.CharField(max_length=256)),
                ('email3_smpt_server', models.CharField(max_length=256)),
                ('email3_imap_server', models.CharField(max_length=256)),
                ('email3_pop3_server', models.CharField(max_length=256)),
                ('email3_password', models.CharField(max_length=256)),
            ],
        ),
    ]
