# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-05-29 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailusers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mojomailmanuser',
            name='email1_password',
        ),
        migrations.RemoveField(
            model_name='mojomailmanuser',
            name='email1_pop3_server',
        ),
        migrations.RemoveField(
            model_name='mojomailmanuser',
            name='email1_smpt_server',
        ),
        migrations.RemoveField(
            model_name='mojomailmanuser',
            name='email2_password',
        ),
        migrations.RemoveField(
            model_name='mojomailmanuser',
            name='email2_pop3_server',
        ),
        migrations.RemoveField(
            model_name='mojomailmanuser',
            name='email2_smpt_server',
        ),
        migrations.RemoveField(
            model_name='mojomailmanuser',
            name='email3_password',
        ),
        migrations.RemoveField(
            model_name='mojomailmanuser',
            name='email3_pop3_server',
        ),
        migrations.RemoveField(
            model_name='mojomailmanuser',
            name='email3_smpt_server',
        ),
        migrations.AddField(
            model_name='mojomailmanuser',
            name='email1_imap_port',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mojomailmanuser',
            name='email1_smtp_port',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mojomailmanuser',
            name='email1_smtp_server',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mojomailmanuser',
            name='email2_imap_port',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mojomailmanuser',
            name='email2_smtp_port',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mojomailmanuser',
            name='email2_smtp_server',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mojomailmanuser',
            name='email3_imap_port',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mojomailmanuser',
            name='email3_smtp_port',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mojomailmanuser',
            name='email3_smtp_server',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mojomailmanuser',
            name='email1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mojomailmanuser',
            name='email1_imap_server',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mojomailmanuser',
            name='email2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mojomailmanuser',
            name='email2_imap_server',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mojomailmanuser',
            name='email3',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mojomailmanuser',
            name='email3_imap_server',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
