# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-27 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailusers', '0002_auto_20160530_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaddress',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='email',
            field=models.CharField(blank=True, default='XX', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
