# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-28 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailusers', '0003_auto_20160727_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaddress',
            name='email_configured',
            field=models.CharField(blank=True, default='False', max_length=255, null=True),
        ),
    ]
