# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-28 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailusers', '0005_auto_20160728_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaddress',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='num_new_emails',
            field=models.IntegerField(default=0),
        ),
    ]
