# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-28 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailusers', '0006_auto_20160728_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
