# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-28 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailusers', '0007_auto_20160728_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
